# Generated by Django 3.2.6 on 2022-05-29 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('active', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=7)),
                ('typeSection', models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='on', max_length=7)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('titleStatus', models.CharField(choices=[('draft', 'Draft'), ('visible', 'Visible')], default='visible', max_length=10)),
                ('subtitleStatus', models.CharField(choices=[('draft', 'Draft'), ('visible', 'Visible')], default='visible', max_length=10)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnailOption', models.CharField(choices=[('draft', 'Draft'), ('visible', 'Visible')], default='visible', max_length=10, null=True)),
                ('thumbnailTypes', models.CharField(choices=[('unique', 'Unique'), ('multiple', 'Multiple')], default='unique', max_length=10, null=True)),
                ('thumbnailStatus', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=7, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('videoTypes', models.CharField(choices=[('unique', 'Unique'), ('multiple', 'Multiple')], default='unique', max_length=10, null=True)),
                ('videoOptions', models.CharField(choices=[('draft', 'Draft'), ('visible', 'Visible')], default='unique', max_length=10, null=True)),
                ('videoStatus', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=7, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
