# Generated by Django 3.2.6 on 2022-05-29 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bxlanding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsectionmodel',
            name='typeSection',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='default', max_length=7),
        ),
        migrations.AlterField(
            model_name='firstsectionmodel',
            name='videoOptions',
            field=models.CharField(choices=[('draft', 'Draft'), ('visible', 'Visible')], default='draft', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AboutSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1500)),
                ('members', models.JSONField()),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
