# Generated by Django 3.2.6 on 2022-05-29 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bxlanding', '0003_showsectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showPlaceName', models.CharField(max_length=250)),
                ('showDate', models.DateTimeField(null=True)),
                ('showCountry', models.CharField(max_length=250)),
                ('showState', models.CharField(max_length=250)),
                ('showAddress', models.CharField(max_length=500)),
                ('showPostalCode', models.CharField(max_length=250)),
                ('showLatitude', models.IntegerField()),
                ('showLongitude', models.IntegerField()),
                ('showThumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('showStatus', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True)),
                ('showStatusProgress', models.CharField(choices=[('postponed', 'Postponed'), ('progress', 'Progress'), ('cancelled', 'Cancelled')], default='progress', max_length=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
